name: atomdisc
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip>=24.0
  - cudnn=8.9
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - numpy=1.25.2
  - pandas=2.2.3
  - scikit-learn=1.7.0
  - rdkit=2024.03.5
  - tqdm=4.66.5
  - pip:
      - -r requirements.txt

